### ISSUE TITLE
Problem with the bapcod library

### ISSUE THREAD

**Issue by brunomattos1** [artalvpes/CVRPSolverDemo#3]
I tried running the demo by following the instructions in the README section, but I encountered the following error: "LoadError: could not load library '/home/bruno/Documentos/libbapcod-shared.so' 'libcplex201.so': non-existent file."

Initially, I thought this issue was due to using CPLEX 12.10, so I installed CPLEX 20.1. However, this led to a new error: "LoadError: could not load library '/home/bruno/Documentos/libbapcod-shared.so' /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/bruno/Documentos/libbapcod-shared.so)."

To resolve this new error, I tried using my own compiled version of the bapcod library instead of the provided one. This solution worked, even with CPLEX 12.10.

OS: Ubuntu 18.04 LTS
Julia version: 1.10.5

**Comment by artalvpes** [comment]
I added an additional binary file for CPLEX version 12.10 and GLIBC version 2.27. Now binaries are organized in folders indicating the OS, CPLEX version and GLIBC version (the last two only for Linux).
